django_app/django_app/urls.py
from django.contrib import admin
from django.urls import path,include #includeで別のファイルを見る関数

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')), #hello/があったら、helloのurlを参照
    path('sns/', include('sns.urls')),
]

django_app/sns/urls.py
from django.urls import path
from . import views #.はカレントディレクトリを表す

app_name = 'sns'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:page>', views.index, name='index'),
    path('edit/<int:num>', views.edit, name='edit'),
    path('delete/<int:num>', views.delete, name='delete'),
    path('post', views.post, name='post'),
    path('post/<int:num>', views.post, name='post'),
    path('filter/', views.filter, name='filter'),
    path('filter/<int:num>', views.filter, name='filter'),
    path('goods', views.goods, name='goods'),
    path('good/<int:good_id>', views.good, name='good'),
]

django_app/sns/models.py
from django.db import models
from django.contrib.auth.models import User

#Messageクラスです
class Message(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='message_owner')
    content = models.TextField(max_length=1000)
    good_count = models.IntegerField(default=0)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '"' + str(self.content) + '     : ' + str(self.owner) + '"'

    class Meta:
        ordering = ('-pub_date',)

#Goodクラスです
class Good(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='good_owner')
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.message) + '        @' + str(self.owner) + '  , good!'

    class Meta:
        ordering = ('-pub_date',)

django_app/sns/forms.py
from django import forms
from  .models import Message,Good
from django.contrib.auth.models import User

#messageフォームです
class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['content']

django_app/sns/views.py
from importlib.resources import contents
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.decorators import login_required

from .models import Message, Good
from .forms import MessageForm

# indexビュー関数です
@login_required(login_url='/admin/login/') #login時にのみindexビュー関数を呼び出して使用出来ます
def index(request, page=1):
    max = 10 #ページに表示する件数
    form = MessageForm()
    msgs = Message.objects.all()
    #ページネーション
    paginate = Paginator(msgs, max)
    page_items = paginate.get_page(page)
    params = {
        'login_user':request.user,
        'form':form,
        'contents':page_items,
    }
    return render(request, 'sns/index.html', params)

# goods関数です（いいねリストページ）
@login_required(login_url='/admin/login/') #login時にのみgoodsリストページ関数を呼び出して使用出来ます
def goods(request):
#ログインユーザーのもうgoodしたmessageを絞り込み取得
    goods = Good.objects.filter(owner=request.user)
    params = {
        'login_user':request.user,
        'contents':goods,
    }
    return render(request, 'sns/good.html', params)

# edit関数です
@login_required(login_url='/admin/login/') #login時にのみedit関数を呼び出して使用出来ます
def edit(request, num):
    obj = Message.objects.get(id=num)
    if (request.method == 'POST'):
        form = MessageForm(request.POST, instance=obj)
        if form.is_valid(): #バリデーションがOKの時
            post = form.save(commit=False) #messageFormの内容をインスタンスに保存する前処理
            post.owner = request.user #messageテーブルにログインしている人のレコードを保存
            post.save()
            return redirect(to='/sns/post') #送信したら投稿リストページにリダイレクト、edit関数の処理を呼ぶ\
        else:
            form = MessageForm(request.POST, instance=obj)
            params = {
            'login_user':request.user,
            'id': num,
            'form': MessageForm(instance=obj),
            }
    return render(request, 'sns/edit.html', params)

# delete関数です
@login_required(login_url='/admin/login/') #login時にのみdelete関数を呼び出して使用出来ます
def delete(request, num):
    messages = Message.objects.get(id=num)
    if (request.method == 'POST'):
            messages.delete()
            return redirect(to='/sns/post') #送信したら投稿リストページにリダイレクト
    params = {
            'login_user':request.user,
            'id': num,
            'item':messages,
            }
    return render(request, 'sns/delete.html', params)

# filter関数です
@login_required(login_url='/admin/login/') #login時にのみfilter関数を呼び出して使用出来ます
def filter(request, num):
    uname = User.objects.get(id=num)
    messages = Message.objects.filter(owner=uname)
    params = {
            'login_user':request.user,
            'userid':num,
            'username':uname,
            'contents':messages,
    }
    return render(request, 'sns/filter.html', params)

# postビュー関数です
@login_required(login_url='/admin/login/') #login時にのみpost関数を呼び出して使用出来ます
def post(request):
    #post送信処理
    if request.method == 'POST':
    #送信内容取得
        form = MessageForm(request.POST)
    #バリデーションがOK
        form.is_valid()
        post = form.save(commit=False) #messageFormの内容をインスタンスに保存する前処理
        post.owner = request.user #messageテーブルにログインしている人のレコードを保存
        post.save()
        return redirect(to='/sns/') #送信したらトップページにリダイレクト、index関数の処理を呼ぶ
    else:
        messages = Message.objects.filter(owner=request.user)
        params = {
            'login_user':request.user,
            'contents':messages,
            }
    return render(request, 'sns/post.html', params)

# good関数、いいねボタンの処理です
@login_required(login_url='/admin/login/') #login時にのみgood関数を呼び出して使用出来ます
def good(request, good_id):
    #goodいいねmessageを取得
    good_msg = Message.objects.get(id=good_id)
    #goodいいねの数の確認
    is_good = Good.objects.filter(owner=request.user).filter(message=good_msg).count()
    #ゼロより大きいか確認（good済なのか判定）
    if is_good > 0:
    #ログインユーザーgood済のgood解除したいmessageを取得
        reject_good_msg = Message.objects.get(id=good_id)
    #ログインユーザーgood済のgood解除したいmessage総数の確認
        is_good = Good.objects.filter(owner=request.user).filter(message=reject_good_msg).count()
    #goodいいねレコードインスタンスを削除(goodいいねした後、goodいいね数を0クリア)
        Good.objects.filter(owner=request.user).filter(message=reject_good_msg).delete()
    #システムメッセージをアラート表示
        messages.success(request, 'Goodを解除しました')
    #相手のgoodいいね    を解除したので、いいねを減らす処理
        reject_good_msg.good_count -= 1
    #goodいいね解除、マイナス1を保存
        reject_good_msg.save()
        return redirect(to='/sns') #送信したらトップページにリダイレクト、index関数の処理を呼ぶ
    else:
    #goodいいねレコードインスタンスを削除
        Good.objects.filter(owner=request.user).filter(message=good_msg).delete()
    #相手のgoodいいねmessageのgoodいいねカウントを足す
        good_msg.good_count += 1
    #goodいいね数1プラスをを保存
        good_msg.save()
    #インスタンスを作成してgoodいいねを保存（いいね数1プラスを保存）
        good = Good()
    #ログインユーザーをgoodテーブルに保存
        good.owner = request.user
    #goodいいね数1をgoodテーブルのメッセージに保存
        good.message = good_msg
        good.save()
    #システムメッセージをアラート表示
        messages.success(request, '新しくGoodしました')
    return redirect(to='/sns')

django_app/sns/templates/sns/delete.html
{% extends 'sns/layout.html' %}

{% block title %}Posts_delete{% endblock %}
{% block header %}
<h1 class="display-4 text-primary">{{login_user}}_Posts_delete</h1>
<p class="caption">{{login_user}} のメッセージを削除</p>
{% endblock %}

{% block content %}
<table class="table">

<form action="{% url 'sns:delete' id %}" method="post">
{% csrf_token %}

<tr><th></th><td>
    <p class="fs-4 my-0">
    {{item.content}}
    </p>
    <p class="my-0 text-end">
    <span class="fs-5">
    @ {{item.owner.username}} /
    </span>
    <span class="fs-6">
    ({{item.pub_date}})
    </span>
    </p>
    <input type="submit" value="delete" class="btn btn-primary mt-2">
    </td></th></tr>

    </table>
</form>
{% endblock %}

</body>
</html>

django_app/sns/templates/sns/edit.html
{% extends 'sns/layout.html' %}

{% block title %}Posts_edit{% endblock %}

{% block header %}
<h1 class="display-4 text-primary">{{login_user}}_Posts_Edit</h1>
<p class="caption">{{login_user}} のメッセージを編集</p>
{% endblock %}

{% block content %}
<form action="{% url 'sns:edit' id %}" method="post">
        {% csrf_token %}
    <table class="table">
        {{ form.as_table }}
    <tr><th><td>
    <input type="submit" value="edit" class="btn btn-primary mt-2">
    </td></th></tr>
    </table>
</form>
{% endblock %}

</body>
</html>

django_app/sns/templates/sns/filter.html
{% extends 'sns/layout.html' %}

{% block title %}Filter{% endblock %}
{% block header %}
<h1 class="display-4 text-primary">{{username}}_Posts</h1>
<p class="caption">{{username}} の投稿したメッセージ</p>
{% endblock %}

{% block content %}
<table class="table mt-3">
<tr>
    <th>Messages</th>
</tr>
    {% for item in contents %}
<tr>
    <td>
    <p class="fs-4 my-0">
    {{item.content}}
    </p>
    <p class="my-0 text-end">
        <span class="fs-5">
        @ {{item.owner.username}} /
        </span>
        <span class="fs-6">
        ({{item.pub_date}})
        </span>
    </p>
    <p class="mt-1 fs-6 text-end">
    <span class="h-6 text-primary">
        good={{item.good_count}}
    </span>
    <span class="float-right">
    <a href="{% url 'sns:good' item.id %}">
    <button class="py-0 px-1 btn btn-outline-primary">good!</button></a>
    </span>
    </p>
    </td>
</tr>
    {% endfor %}
</table>
{% endblock %}

django_app/sns/templates/sns/good.html
{% extends 'sns/layout.html' %}

{% block title %}Goods{% endblock %}

{% block header %}
<h1 class="display-4 text-primary">{{login_user}}_Goods</h1>
<p class="caption">{{login_user}} がGoodしたメッセージ</p>
{% endblock %}

{% block content %}
<table class="table mt-3">
<tr>
    <th>Messages</th>
</tr>
    {% for item in contents %}
<tr><td>
    <p class="fs-5">
    {{item}}</p>
    </td>
</tr>
    {% endfor %}
</table>
{% endblock %}

django_app/sns/templates/sns/index.html
{% extends 'sns/layout.html' %}

{% block title %}Index{% endblock %}

{% block header %}
<h1 class="display-4 text-primary">SNS</h1>

{% if messages %}
<div class="alert alert-primary alert-dismissible fade show" role="alert">

{% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %}
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
</div>
{% endif %}
{% endblock %}

{% block content %}
<form action="{% url 'sns:post' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
<button class="btn btn-primary">Post!</button>
</form>
<hr>
<table class="table mt-3">
<tr>
    <th>Messages</th>
</tr>
    {% for item in contents %}
<tr>
    <td>
    <p class="fs-4 my-0">
    {{item.content}}
    </p>
    {% if item.owner == login_user %}
    <span class="fs-5">
        <a href="{% url 'sns:edit' item.id %}">edit</a> |
        <a href="{% url 'sns:delete' item.id %}">delete</a>
    </span>
    {% endif %}
    <p class="my-0 text-end">
    {% if item.owner == login_user %}
    <span class="fs-5">
    @ <a href="{% url 'sns:post' %}">{{item.owner.username}}</a> /
    </span>
    {% endif %}
    {% if item.owner != login_user %}
    <span class="fs-5">
    @ <a href="{% url 'sns:filter' item.owner.id %}">{{item.owner.username}}</a> /
    </span>
    {% endif %}
    <span class="fs-6">
    ({{item.pub_date}})
    </span>
    </p>
    <p class="mt-1 fs-6 text-end">
    <span class="h-6 text-primary">
    good={{item.good_count}}
    </span>
    <span class="float-right">
    {% if item.owner != login_user %}
    <a href="{% url 'sns:good' item.id %}">
    <button class="py-0 px-1 btn btn-outline-primary">good!</button></a>
    {% endif %}
    </span>
    </p>
    </td>
</tr>
    {% endfor %}
</table>

<ul class="pagination justify-content-center">
{% if contents.has_previous %}
<li class="page-item">
<a class="page-link" href="{% url '/sns/' %}">
    &laquo; first</a>
</li>
<li class="page-item">
<a class="page-link" href="/sns/{{contents.previous_page_number}}">
    &laquo; prev</a>
</li>
{% else %}
<li class="page-item">
<a class="page-link">
    &laquo; first</a>
</li>
<li class="page-item">
<a class="page-link">
    &laquo; prev</a>
</li>
{% endif %}
<li class="page-item">
<a class="page-link">
    {{contents.number}}/{{contents.pagenator.num_pages}}</a>
</li>
{% if contents.has_next %}
<li class="page-item">
<a class="page-link" href="/sns/{{contents.next_page_number}}">
    next &raquo;</a>
</li>
<li class="page-item">
<a class="page-link" href="/sns/{{contents.paginator.num_pages}}">
    last &raquo;</a>
</li>
{% else %}
<li class="page-item">
<a class="page-link">
    next &raquo;</a>
</li>
<li class="page-item">
<a class="page-link">
    last &raquo;</a>
</li>
{% endif %}
</ul>
{% endblock %}

django_app/sns/templates/sns/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.bundle.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" rel="stylesheet" crossorigin="anonymous">
</head>
<body>
<nav class="navbar fixed-top navbar-expand navbar-light bg-light">
<ul style="width:100%" class="navbar-nav mr-auto">
<li class="nav-item">
<a class="nav-link" href="{% url 'sns:index' %}">top</a>
</li>
<li class="nav-item">
<a class="nav-link" href="{% url 'sns:post' %}">post</a>
</li>
<li class="nav-item">
<a class="nav-link" href="{% url 'sns:goods' %}">goods</a>
</li>
<li class="nav-item nav-link fw-bold text-primary">
@ {{login_user}} Logined.
</li>
</nav>
<div class="container">
    <div style="padding-top:3.5em;">
        {% block header %}
        {% endblock %}
    </div>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    <div class="my-3 text-center">
        <span class="font-weight-bold">
            <a href="/admin/logout?next=/sns/">
            [ logout ]</a>
        </span>
        <span class="float-right">&copy; 2024 KoYURIKO.
        </span>
    </div>
</div>
</body>
</html>

django_app/sns/templates/sns/post.html
{% extends 'sns/layout.html' %}

{% block title %}Post{% endblock %}
{% block header %}
<h1 class="display-4 text-primary">{{login_user}}_Posts</h1>
<p class="caption">{{login_user}} の投稿したメッセージ</p>
{% endblock %}

{% block content %}
<table class="table mt-3">
<tr>
    <th>Messages</th>
</tr>
    {% for item in contents %}
<tr>
    <td>
    <p class="fs-4 my-0">
    {{item.content}}
    <span class="fs-5">
    {% if item.owner == login_user %}
    <a href="{% url 'sns:edit' item.id %}">edit</a>
    |
    <a href="{% url 'sns:delete' item.id %}">delete</a>
    {% endif %}
    </span>
    </p>
    <p class="my-0 text-end">
        <span class="fs-6">
        ({{item.pub_date}})
        </span>
    </p>
    <p class="my-0 text-end text-info">
    good={{item.good_count}}
    </p>
    </td>
</tr>
    {% endfor %}
</table>
{% endblock %}