django_app/django_app/urls.py
from django.contrib import admin
from django.urls import path,include #includeで別のファイルを見る関数

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')), #hello/があったら、helloのurlを参照
    path('sns/', include('sns.urls')),
]

django_app/hello/urls.py
from django.urls import path
# from .views import IndexView
from . import views #.はカレントディレクトリを表す

app_name = 'hello'

urlpatterns = [
    # path('', IndexView.as_view(), name='index'),
    path('', views.index, name='index'),
    path('<int:num>', views.index, name='index'),
    path('create', views.create, name='create'),
    path('edit/<int:num>', views.edit, name='edit'),
    path('delete/<int:num>', views.delete, name='delete'),
    path('find', views.find, name='find'),
    path('check', views.check, name='check'),
    path('message/', views.message, name='message'),
    path('message/<int:page>', views.message, name='message'),
    # path('form', views.form, name='form'),
]

django_app/sns/urls.py
from django.urls import path
from . import views #.はカレントディレクトリを表す

app_name = 'sns'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:page>', views.index, name='index'),
    path('edit/<int:num>', views.edit, name='edit'),
    path('delete/<int:num>', views.delete, name='delete'),
    path('post', views.post, name='post'),
    path('post/<int:num>', views.post, name='post'),
    path('filter/', views.filter, name='filter'),
    path('filter/<int:num>', views.filter, name='filter'),
    path('goods', views.goods, name='goods'),
    path('good/<int:good_id>', views.good, name='good'),
]

django_app/hello/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator,MinLengthValidator,MaxLengthValidator

class Friend(models.Model):
    name = models.CharField(max_length=100, validators=[MinLengthValidator(1)])
    mail = models.EmailField(max_length=200, validators=[MinLengthValidator(1)])
    gender = models.BooleanField()
    age = models.IntegerField(validators=[ \
        MinValueValidator(0), \
            MaxValueValidator(150)])
    birthday = models.DateField()

#インスタンスの内容
    def __str__(self):
        return '<Friends:id=' + str(self.id) + ', ' + \
            self.name + '(' + str(self.age) + ')>'
    
class Message(models.Model):
    friend = models.ForeignKey(Friend, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=300)
    pub_date = models.DateTimeField(auto_now_add=True)

#インスタンスの内容
    def __str__(self):
        return '<Message:id=' + str(self.id) + ', ' + \
            self.title + '(' + str(self.pub_date) + ')>'
    
class Meta:
    ordering = ('pub_date',)

django_app/hello/forms.py
from typing import Any
from django import forms
from .models import Friend,Message

class FriendForm(forms.ModelForm):
  class Meta:
    model = Friend
    fields = ['name','mail','gender','age','birthday']
    widget = {
      'name': forms.TextInput(attrs={'class':'form-control'}),
      'mail': forms.EmailInput(attrs={'class':'form-control'}),
      'age': forms.NumberInput(attrs={'class':'form-control'}),
      'birthday': forms.DateInput(attrs={'class':'form-control'})
    }
  # name = forms.CharField(label='Name', \
  #   widget=forms.TextInput(attrs={'class':'form-control'}))
  # mail = forms.EmailField(label='Email', \
  #   widget=forms.EmailInput(attrs={'class':'form-control'}))
  # gender = forms.BooleanField(label='Gender', required=False, \
  #   widget=forms.CheckboxInput(attrs={'class':'form-check'}))
  # age = forms.IntegerField(label='Age', \
  #   widget=forms.NumberInput(attrs={'class':'form-control'}))
  # birthday = forms.DateField(label='Birth', \
  #   widget=forms.DateInput(attrs={'class':'form-control'}))

class FindForm(forms.Form):
  find = forms.CharField(label='Find', required=False, \
    widget=forms.TextInput(attrs={'class':'form-control'}))

class CheckForm(forms.Form):
  str = forms.CharField(label='Name', \
    widget=forms.TextInput(attrs={'class':'form-control'}))

#   requied = forms.IntegerField(label='Required', \
#     widget=forms.NumberInput(attrs={'class':'form-control'}))
#   min = forms.IntegerField(label='Min', min_value=100, \
# widget=forms.NumberInput(attrs={'class':'form-control'}))
#   max = forms.IntegerField(label='Max', max_value=1000, \
#     widget=forms.NumberInput(attrs={'class':'form-control'}))
  
  # def clean(self):
  #   clean_data = super.clean()
  #   str = clean_data['str']
  #   if (str.lower().starswitch('no')):
  #     raise forms.ValidationError('You input "NO"')

class MessageForm(forms.ModelForm):
  class Meta:
    model = Message
    fields = ['title','content','friend']
    widget = {
      'title': forms.TextInput(attrs={'class':'form-control form-control-sm'}),
      'content': forms.Textarea(attrs={'class':'form-control form-control-sm', 'rows':2}),
      'friend': forms.Select(attrs={'class':'form-control form-control-sm'}),
    }

django_app/hello/views.py
from django.shortcuts import render
from django.shortcuts import redirect
# from django.views.generic import FormView
from django.http import HttpResponse
from django.db.models import Count,Sum,Avg,Min,Max
from django.core.paginator import Paginator

from .models import Friend, Message
from .forms import FriendForm, MessageForm, FindForm
# from .forms import HelloForm,FindForm, CheckForm, 

# helloアプリの内容を書き換え
# index関数です

def index(request, num=1):
    data = Friend.objects.all()
    page = Paginator(data, 3) #3件づつリスト表示
    params = {
        'title': 'Hello',  # 動的にページに属性を与えます
        'message': '',
        'data': page.get_page(num),
    }
    # data = Friend.objects.all().order_by('age')  # ソート・昇順
    # data = Friend.objects.all().order_by('-age') #ソート・降順
    # data = Friend.objects.all().order_by('age').reverse() #ソート・逆順
    # re1 = Friend.objects.aggregate(Count('age'))
    # re2 = Friend.objects.aggregate(Sum('age'))/
    # re3 = Friend.objects.aggregate(Avg('age'))
    # re4 = Friend.objects.aggregate(Min('age'))
    # re5 = Friend.objects.aggregate(Max('age'))
    # msg = 'Sort as age<br>count:' + str(re1['age__count']) \
    #     + '<br>Sum:' + str(re2['age__sum']) \
    #     + '<br>Average:' + str(re3['age__avg']) \
    #     + '<br>Min:' + str(re4['age__min']) \
    #     + '<br>Max:' + str(re5['age__max'])
    return render(request, 'hello/index.html', params)

# Message関数です

def message(request, page=1):
    if (request.method == 'POST'):
        # obj = Message()
        # form = MessageForm(request.POST, instance=obj)
        form = MessageForm(request.POST)
        form.save()
    data = Message.objects.all()
    paginator = Paginator(data, 5) #5件づつリスト表示
    params = {
        'title': 'Message',  # 動的にページに属性を与えます
        'form': MessageForm(),
        'data': paginator.get_page(page),
    }
    return render(request, 'hello/message.html', params)

# create関数です

def create(request):
    if (request.method == 'POST'):
        friend = FriendForm(request.POST)
        friend.save()
        return redirect(to='/hello')
    params = {
        'title': 'Hello',  # 動的にページに属性を与えます
        'form': FriendForm(),
    }
    return render(request, 'hello/create.html', params)

# edit関数です

def edit(request, num):
    obj = Friend.objects.get(id=num)
    if (request.method == 'POST'):
        friend = FriendForm(request.POST, instance=obj)
        friend.save()
        return redirect(to='/hello')
    params = {
        'title': 'Hello',  # 動的にページに属性を与えます
        'id': num,
        'form': FriendForm(instance=obj),
    }
    return render(request, 'hello/edit.html', params)

# delete関数です

def delete(request, num):
    friend = Friend.objects.get(id=num)
    if (request.method == 'POST'):
        friend.delete()
        return redirect(to='/hello')
    params = {
        'title': 'Hello',  # 動的にページに属性を与えます
        'id': num,
        'obj': friend,
    }
    return render(request, 'hello/delete.html', params)

# find関数です

def find(request):
    if (request.method == 'POST'):
        msg = 'search result:'
        form = FindForm(request.POST)
        find = request.POST['find']
        list = find.split()
        data = Friend.objects.all()[int(list[0]):int(list[1])]
    else:
        msg = 'search words...'
        form = FindForm()
        data = Friend.objects.all()
    params = {
        'title': 'Hello',
        'message': msg,
        'form': form,
        'data': data,
    }
    return render(request, 'hello/find.html', params)

# check関数です

def check(request):
    params = {
        'title': 'Hello',
        'message': 'check validation.',
        'form': FriendForm(),
    }
    if (request.method == 'POST'):
        obj = Friend()
        form = FriendForm(request.POST, instance=obj)
        params['form'] = form
        if (form.is_valid()):
            params['message'] = 'OK:入力内容の不備はありません'
        else:
            params['message'] = 'NO good:チェックの結果、入力の不備があります'
    return render(request, 'hello/check.html', params)

# def find(request):
#     if (request.method == 'POST'):
#         msg = 'Search result:'
#         form = FindForm(request.POST)
#         find = request.POST['find']
#         list = find.split()
#         data = Friend.objects.all()[int(list[0]):int(list[1])]
#     else:
#         msg = 'Search words....'
#         form = FindForm()
#         data = Friend.objects.all()
#     params = {
#         'title': 'Hello',  # 動的にページに属性を与えます
#         'message': msg,
#         'form': form,
#         'data': data,
#     }
    # return render(request, 'hello/find.html', params)

    #    name = request.POST['name']
    #    mail = request.POST['mail']
    #    gender = 'gender' in request.POST
    #    age = int(request.POST['age'])
    #    birth = request.POST['birthday']
    #    friend = Friend(name=name,mail=mail,gender=gender, \
    #                    age=age,birthday=birth)
    #    friend.save()
    #    return redirect(to='/hello')
    # return render(request, 'hello/create.html', params)


# def index(request):
#     data = Friend.objects.all().values('id', 'name')
#     params = {
#         'title': 'Hello',  # 動的にページに属性を与えます
#         'data': data,
#     }
    # data = Friend.objects.all()
    # params = {
    #     'title': 'Hello',  # 動的にページに属性を与えます
    #     'message': 'all friends.',
    #     'data': [],
    #     'form': HelloForm()
    # }
    # if (request.method == 'POST'):
    #     num=request.POST['id']
    #     item = Friend.objects.get(id=num)
    #     params['data'] = [item]
    #     params['form'] = HelloForm(request.POST)
    # else:
    #     params['data'] = Friend.objects.all()

    # if (request.method == 'POST'):
    #     params['message'] = '名前:' + request.POST['name'] + \
    #     '<br>メール:' + request.POST['mail'] + \
    #     '<br>年齢:' + request.POST['age']
    #     params['form'] = HelloForm(request.POST)
    # return render(request, 'hello/index.html', params)


# class IndexView(FormView):
#     template_name = 'hello/index.html'
#     form_class = HelloForm
#     # success_url = '/'

#     def __init__(self):
#         self.params = {
#             'title': 'Hello',
#             'message': 'your data:',
#             'form': self.form_class(),
#         }

#     def get(self, request):
#         return render(self.request, self.template_name, self.params)

#     def form_valid(self, form):
#         self.params["message"] = '名前:{}<br>メール:{}<br>年齢:{}'.format(
#             form.cleaned_data['name'],
#             form.cleaned_data['mail'],
#             form.cleaned_data['age'],
#         )
#         print(self.request.POST)
#         self.params['form'] = self.form_class(self.request.POST)
#         return render(self.request, self.template_name, self.params)


# def index(request):
#     params = {
#         'title': 'Hello/index',  # 動的にページに属性を与えます
#         'msg': 'お名前は？',
#         # 'goto': 'next',
#     }
#     return render(request, 'hello/index.html', params)


# def form(request):
#     msg = request.POST['msg']
#     params = {
#         'title': 'Hello/Form',  # 動的にページに属性を与えます
#         'msg': 'こんにちは！' + msg + 'さん',
#         # 'goto': 'next',
#     }
#     return render(request, 'hello/index.html', params)

# def next(''request):
#     params = {
#         'title': 'Hello/Next',
#         'msg': 'デザイン制作の次のページです。',
#         'goto': 'index',
#     }
# return render(request, 'hello/index.html', params)

# def index(request):
# helloアプリの内容を書き換え
# return HttpResponse('Hello Django!')
# msg = request.GET['keys1']
# return HttpResponse('you typed:"' + msg + '".')

django_app/hello/templates/hello/check.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" rel="stylesheet" crossorigin="anonymous">
</head>
<body class="container">
<h1 class="display-4 text-primary">{{title}}</h1>
<p>{{message|safe}}</p>
<ol class="list-group mb-4">
{% for item in form %}
<li class="list-group-item py-2">
    {{ item.name }}({{ item.value }})
    :{{ item.errors.as_text }}</li>
{% endfor %}
</ol>
<form action="{% url 'hello:check' %}" method="POST">
{% csrf_token %}
<div class="form-group">名前{{ form.name }}</div>
<div class="form-group">メール{{ form.mail }}</div>
<div class="form-group">性別{{ form.gender }}</div>
<div class="form-group">年齢{{ form.age }}</div>
<div class="form-group">誕生日{{ form.birthday }}</div>
<div class="form-group"><input type="submit" value="GO" class="btn btn-primary"></div>
</form>
</body>
</html>

django_app/hello/templates/hello/create.html
{% load static%}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" crossorigin="anonymous">
</head>
<body class="container">
    <h1 class="display-4 text-primary">{{title}}</h1>
    <form action="{% url 'create' %}" method="post">
        {% csrf_token %}
    <table class="table">
        {{ form.as_table }}
    <tr><th><td>
    <input type="submit" value="GO" class="btn btn-primary mt-2">
    </td></th></tr>
    </table>
    </form>

</body>
</html>

django_app/hello/templates/hello/delete.html
{% load static%}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" crossorigin="anonymous">
</head>
<body class="container">
    <h1 class="display-4 text-primary">{{title}}</h1>
    <p>※以下のレコードを削除します</p>
    <table class="table">
    <tr><th>ID</th><td>{{obj.id}}</td></tr>
    <tr><th>Name</th><td>{{obj.name}}</td></tr>
    <tr><th>Gender</th><td>
    {% if obj.gender == False %}Male{% endif %}
    {% if obj.gender == True %}Female{% endif %}</td></tr>
    <tr><th>Email</th><td>{{obj.mail}}</td></tr>
    <tr><th>Age</th><td>{{obj.age}}</td></tr>
    <tr><th>Birth</th><td>{{obj.birthday}}</td></tr>
    <form action="{% url 'delete' id %}" method="post">
        {% csrf_token %}
    <tr><th></th><td>
    <input type="submit" value="GO" class="btn btn-primary">
    </td></tr>
    </form>
    </table>
</body>
</html>

django_app/hello/templates/hello/edit.html
{% load static%}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" crossorigin="anonymous">
</head>
<body class="container">
    <h1 class="display-4 text-primary">{{title}}</h1>
    <form action="{% url 'edit' id %}" method="post">
        {% csrf_token %}
    <table class="table">
        {{ form.as_table }}
    <tr><th><td>
    <input type="submit" value="GO" class="btn btn-primary mt-2">
    </td></th></tr>
    </table>
    </form>

</body>
</html>

django_app/hello/templates/hello/find.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" rel="stylesheet" crossorigin="anonymous">
</head>
<body class="container">
    <h1 class="display-4 text-primary">{{title}}</h1>
    <p>{{message|safe}}</p>
    <form action="{% url 'hello:find' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <tr><th></th><td>
        <input type="submit" value="GO" class="btn btn-primary mt-2">
    </form>
    <hr>
    <table class="table">
    <tr>
    <th>id</th>
    <th>name</th>
    <th>age</th>
    <th>mail</th>
    <th>birthday</th>
    </tr>
    {% for item in data %}
    <tr>
    <th>{{item.id}}</th>
    <td>{{item.name}}</td>
    <td>{{item.age}}</td>
    <td>{{item.mail}}</td>
    <td>{{item.birthday}}</td>
    </tr>
    {% endfor %}
</table>
</body>
</html>

django_app/hello/templates/hello/index.html
{% load static%}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" crossorigin="anonymous">
    {% comment %} <link rel="stylesheet" type="text/css" href="/static/hello/css/style.css"> {% endcomment %}
</head>
<body class="container">
<h1 class="display-4 text-primary">{{title}}</h1>
<p>{{message|safe}}</p>
<table class="table">
<tr>
    <th>id</th>
    <th>name</th>
    <th>age</th>
    <th>mail</th>
    <th>birthday</th>
</tr>
    {% for item in data %}
<tr>
    <td>{{item.id}}</td>
    <td>{{item.name}}</td>
    <td>{{item.age}}</td>
    <td>{{item.mail}}</td>
    <td>{{item.birthday}}</td>
</tr>
{% comment %} <tr>
    <td>{{item}}</td>
    <td><a href="{% url 'edit' item.id %}">Edit</a></td>
    <td><a href="{% url 'delete' item.id %}">Delete</a></td>
</tr> {% endcomment %}
    {% endfor %}
    </table>

<ul class="pagination justify-content-center">
{% if data.has_previous %}
<li class="page-item">
<a class="page-link" href="{% url 'hello:index' %}">
    &laquo; first</a>
</li>
<li class="page-item">
<a class="page-link" href="{% url 'hello:index' %}{{data.previous_page_number}}">
    &laquo; prev</a>
</li>
{% else %}
<li class="page-item">
<a class="page-link">
    &laquo; first</a>
</li>
<li class="page-item">
<a class="page-link">
    &laquo; prev</a>
</li>
{% endif %}
<li class="page-item">
<a class="page-link">
    {{data.number}}/{{data.pagenator.num_pages}}</a>
</li>
{% if data.has_next %}
<li class="page-item">
<a class="page-link" href="{% url 'hello:index' %}{{data.next_page_number}}">
    next &raquo;</a>
</li>
<li class="page-item">
<a class="page-link" href="{% url 'hello:index' %}{{data.paginator.num_pages}}">
    last &raquo;</a>
</li>
{% else %}
<li class="page-item">
<a class="page-link">
    next &raquo;</a>
</li>
<li class="page-item">
<a class="page-link">
    last &raquo;</a>
</li>
{% endif %}
</ul>
</body>
</html>

django_app/hello/templates/hello/message.html
{% load static%}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" crossorigin="anonymous">
    {% comment %} <link rel="stylesheet" type="text/css" href="/static/hello/css/style.css"> {% endcomment %}
</head>
<body class="container">
<h1 class="display-4 text-primary">{{title}}</h1>
<form action="{% url 'hello:message' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
<input type="submit" value="GO" class="btn btn-primary mt-2">
<div class="mt-5"></div>
{% comment %} </form> {% endcomment %}
<table class="table">
<tr>
    <th class="py-1">title</th>
    <th class="py-1">name</th>
    <th class="py-1">datetime</th>
</tr>
    {% for item in data %}
<tr>
    <td class="py-2">{{item.title}}</td>
    <td class="py-2">{{item.friend.name}}</td>
    <td class="py-2">{{item.pub_date}}</td>
</tr>
    {% endfor %}
</table>

<ul class="pagination justify-content-center">
{% if data.has_previous %}
<li class="page-item">
<a class="page-link" href="{% url 'hello:message' %}">
    &laquo; first</a>
</li>
<li class="page-item">
<a class="page-link" href="{% url 'hello:message' %}{{data.previous_page_number}}">
    &laquo; prev</a>
</li>
{% else %}
<li class="page-item">
<a class="page-link">
    &laquo; first</a>
</li>
<li class="page-item">
<a class="page-link">
    &laquo; prev</a>
</li>
{% endif %}
<li class="page-item">
<a class="page-link">
    {{data.number}}/{{data.pagenator.num_pages}}</a>
</li>
{% if data.has_next %}
<li class="page-item">
<a class="page-link" href="{% url 'hello:message' %}{{data.next_page_number}}">
    next &raquo;</a>
</li>
<li class="page-item">
<a class="page-link" href="{% url 'hello:message' %}{{data.paginator.num_pages}}">
    last &raquo;</a>
</li>
{% else %}
<li class="page-item">
<a class="page-link">
    next &raquo;</a>
</li>
<li class="page-item">
<a class="page-link">
    last &raquo;</a>
</li>
{% endif %}
</ul>
</body>
</html>